name: 'Auto Release'

on:
  push:
    paths:
      - 'VERSION'

jobs:
  create-github-release:
    name: Deploy GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - name: Get Version
        id: gv
        run: |
          echo "::set-output name=ver::$(cat ./VERSION)"
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: "v${{ steps.gv.outputs.ver }}"
          tag_name: "v${{ steps.gv.outputs.ver }}"
          draft: false
          prerelease: false
  create-el-8-rpm:
    runs-on: ubuntu-latest
    name: 'Build package for EL 8'
    needs: create-github-release
    strategy:
      matrix:
        pe_version:
          - '2021.5.0'
          - '2019.8.10'
    outputs:
      package_name: ${{ steps.el-8-rpm.outputs.filename }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - name: 'Build package'
        uses: ./.github/actions/create-package-for-el-8
        id: 'el-8-rpm'
        with:
          pe-version: ${{ matrix.pe_version }}
      - name: 'Upload package'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-github-release.outputs.upload_url }} 
          asset_path: ./${{ steps.el-8-rpm.outputs.filename }}
          asset_name:  ${{ steps.el-8-rpm.outputs.filename }}
          asset_content_type: mime
  create-el-7-rpm:
    runs-on: ubuntu-latest
    name: 'Build package for EL 7'
    needs: create-github-release
    strategy:
      matrix:
        pe_version:
          - '2021.5.0'
          - '2019.8.10'
    outputs:
      package_name: ${{ steps.el-7-rpm.outputs.filename }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - name: 'Build package'
        uses: ./.github/actions/create-package-for-el-7
        id: 'el-7-rpm'
        with:
          pe-version: ${{ matrix.pe_version }}
      - name: 'Upload package'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-github-release.outputs.upload_url }} 
          asset_path: ./${{ steps.el-7-rpm.outputs.filename }}
          asset_name:  ${{ steps.el-7-rpm.outputs.filename }}
          asset_content_type: mime
  create-ubuntu-18-04-deb:
    runs-on: ubuntu-latest
    name: 'Build package for Ubuntu 18.04'
    needs: create-github-release
    strategy:
      matrix:
        pe_version:
          - '2021.5.0'
          - '2019.8.10'
    outputs:
      package_name: ${{ steps.ubuntu-18-04-deb.outputs.filename }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - name: 'Build package'
        uses: ./.github/actions/create-package-for-ubuntu-18-04
        id: 'ubuntu-18-04-deb'
        with:
          pe-version: ${{ matrix.pe_version }}
      - name: 'Upload package'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-github-release.outputs.upload_url }}
          asset_path: ./${{ steps.ubuntu-18-04-deb.outputs.filename }}
          asset_name:  ${{ steps.ubuntu-18-04-deb.outputs.filename }}
          asset_content_type: mime
